### ISSUE TITLE
ENH: numpy support?

### ISSUE THREAD

**Issue by jankoslavic** [csurfer/pyheatmagic#3]
This is a great magic!!

I wonder why this code is not working:
```
   %%heat 
   def gauss(A, b):
       Ab = np.column_stack((A, b))
       for p, pivot_vrsta in enumerate(Ab[:-1]):
       for vrsta in Ab[p + 1:]:
            if pivot_vrsta[p]:
                vrsta[p:] = vrsta[p:] - pivot_vrsta[p:] * vrsta[p] / pivot_vrsta[p]
            else:
                raise Exception('Division with 0.')
        return Ab

   import numpy as np
   n = 40
   gauss(np.random.random((n, n)),np.random.random(n))
```

**Comment by csurfer** [comment]
@jankoslavic: I ran the same code with probably some indentation fixes and it ran without a glitch for me. The code I ran was:
```python
%%heat
def gauss(A, b):
    Ab = np.column_stack((A, b))
    for p, pivot_vrsta in enumerate(Ab[:-1]):
        for vrsta in Ab[p + 1:]:
            if pivot_vrsta[p]:
                vrsta[p:] = vrsta[p:] - pivot_vrsta[p:] * vrsta[p] / pivot_vrsta[p]
            else:
                raise Exception('Division with 0.')
            return Ab

    import numpy as np
    n = 40
    gauss(np.random.random((n, n)),np.random.random(n))
```
I suspect something wrong with your setup. One easy way to verify is to create a `virtualenv` and install `py-heat-magic` within it. Then run the above. As the magic internally installs all the dependency needed for the above code, it will run and you might get a better idea as to what might be going wrong otherwise.

**Comment by jankoslavic** [comment]
@csurfer I have updated `conda update conda` and then `conda update --all` and now everything works as it should. Thank you for your effort. Great package!
